Handle incorrect channel mask in WAV files
pdeljanov/Symphonia pull request #180
Opened 2023-01-27 09:34 UTC by jesnor

This PR contains a work around for some WAV files that have an incorrect channel mask value. For example VLC can still play them.

2023-01-29 17:39 UTC, pdeljanov commented
Hi @jesnor,

I've considered this workaround before since I've seen a single file with this issue. I didn't implement it because it didn't seem common and also because the channel mapping will be very wrong if > 2 channels.

Do you think we should limit this workaround if only `n_channels` is 1 or 2 (if 0, the workaround shouldn't be applied)? The mapping wouldn't be wrong in that case. Also, we'll definitely need a warning log if the workaround is applied.

Do you also happen to know if the WAV files were produced by a particular app or encoder?

Thanks!

2023-01-29 18:30 UTC, jesnor commented
The file that failed for me had 9 channels, created with Audacity I think. Interestingly similar file with 8 channels had correct channel mask.

Since VLC can play the file, I think the patch is reasonable. It's better to be able to decode something rather than nothing, although the channel mask might be weird.

2023-01-30 02:20 UTC, pdeljanov commented
Found [this](https://learn.microsoft.com/en-us/previous-versions/windows/hardware/design/dn653308(v=vs.85)?redirectedfrom=MSDN#details-about-dwchannelmask) documentation from Microsoft. Looks like `0` just means the channels are not assigned a "position", or are ambiguous and the decoder can device.

We don't have a way to express un-positioned channels with Symphonia's current API, so your solution is valid for all channels then. Only other alternative would be to assume certain channel layouts for each number (i.e., 2.1 for 3, etc.).

Just going to leave a couple small comments and then I'll merge the change once fixed.

2023-01-30 02:24 UTC, pdeljanov requested changes

2023-01-30 02:24 UTC, pdeljanov commented on symphonia-format-wav/src/chunks.rs
> +        if channel_mask == 0 {
If `n_channels` is also 0 then this should be executed because of the next comment.

2023-01-30 02:24 UTC, pdeljanov commented on symphonia-format-wav/src/chunks.rs
> +            channel_mask = (1 << n_channels) - 1;
Add an `info!` log here stating "channel mask is empty, channel positions may be incorrect" or something similar.

2023-01-30 09:04 UTC, jesnor commented on symphonia-format-wav/src/chunks.rs
> +            channel_mask = (1 << n_channels) - 1;
Pushes a better version that should handle all cases (too many/few bits in mask) according to the document you linked.

2023-02-02 03:21 UTC, pdeljanov approved these changes

2023-02-02 03:22 UTC, merged

2023-02-02 03:22 UTC, pdeljanov commented
Thanks! This is great!