Support mulitchannel WAV formats
pdeljanov/Symphonia pull request #194
Opened 2023-03-07 11:07 UTC by jesnor

Problems with some WAV file again :) This is using the "old" WAVEFORMAT file format with multichannel (>2). This fix just maps to the first n channels. I don't know if you want to accept it, I'm not sure if it's allowed in the WAV standard, but at the same time maybe it's better to be able to use the file rather than giving an error.

2023-05-05 02:38 UTC, pdeljanov requested changes
Thanks for this!

I think mirroring the behaviour of VLC or FFmpeg here is reasonable. However, there are some potential issues that need to be taken care of to prevent panics.

2023-05-05 02:38 UTC, pdeljanov commented on symphonia-format-wav/src/chunks.rs
> +        let channels = Channels::from_bits((1 << n_channels) - 1)
This will panic if `n_channels` is > 31 because the `Channels` bit-mask is 32 bits and shifts > 31 is undefined behaviour. So I think we'll need a check to reject files with too many channels or zero channels, and to ensure that the shift logic works for all cases that do pass the check.

It may make sense to even add a `try_new_from_count` (or some other name) function to `Channels` to centralize part of this logic (0 is valid for `Channels` but not for WAVE).

2023-05-05 13:19 UTC, jesnor commented on symphonia-format-wav/src/chunks.rs
> +        let channels = Channels::from_bits((1 << n_channels) - 1)
Added try_channel_count_to_mask function with unit test

2023-05-11 03:06 UTC, pdeljanov approved these changes

2023-05-11 03:11 UTC, merged

2023-05-11 03:12 UTC, pdeljanov commented
Thanks, this looks good to me! Merged!