Feature/aifc
pdeljanov/Symphonia pull request #204
Opened 2023-05-07 18:02 UTC by dedobbin

This allows AiffReader to also read Aifc files. 
It works with all files from https://www.mmsp.ece.mcgill.ca/Documents/AudioFormats/AIFF/Samples.html, with the exception of files with 12bit samples (as discussed, should be supported but for now it doesn't work yet because it causes distortion) and a file that uses sowt compression.

Sowt support could be a cool feature for the future, but i think for now this is already usable.

Let me know what you think

2023-05-30 06:31 UTC, AkiyukiOkayasu commented
I am somewhat concerned that sowt is designed to handle only 16 bits.
I don't think this will be a problem for most use cases, though.
In fact, even ffmpeg fails when trying to convert a wav file to a 24bit little endian AIFF file.
```sh
ffmpeg -i input.wav -c:a pcm_s24le outputS24LE.wav
```

16bit little endian can be converted correctly.
```sh
ffmpeg -i input.wav -c:a pcm_s16le outputS16LE.wav
```

I could not find out if this is a specification of AIFF-C or a limitation of ffmpeg.
The following forum is not definitive, but it seems that libaiff is not limited to 16bit.
https://www.kvraudio.com/forum/viewtopic.php?t=328325

2023-06-04 12:10 UTC, dedobbin commented
Thank you for taking a look! 

"I am somewhat concerned that sowt is designed to handle only 16 bits."

I will try and dig up where i read about this being part of the SOWT encoding. It's not a problem to remove SOWT from this PR, it's rather out of scope anyway, but i couldn't find any files in the wild that disagreed with my implementation, so i figured why not.

Another option is to drop the 16bit constraint. It's not uncommon that some software exports audio files "off spec" to increase compatibility.

2023-06-08 03:52 UTC, pdeljanov requested changes

2023-06-08 03:52 UTC, pdeljanov commented on symphonia-format-riff/src/riff.rs
> -        }
I'm a bit confused about this. Wouldn't deleting some of this break the WAVE reading functionality?

2023-06-08 03:52 UTC, pdeljanov commented on symphonia-format-riff/src/aiff_chunks.rs
> +}
It looks like AIFC has some additional fields in the common chunk that are not present in AIFF. That means that the common chunk for AIFC is a superset of AIFF. So can you put the parsing of the common fields in `self.parse` and then just read the extra fields for AIFC after? This would reduce code duplication!

2023-06-08 03:52 UTC, pdeljanov commented on symphonia-format-riff/src/lib.rs
> +        };
You probably don't really need to introduce a new `enum` for this. Just use match the `riff_form` string like this below when you parse the common chunk.

2023-06-08 03:52 UTC, pdeljanov commented on symphonia-format-riff/src/aiff_chunks.rs
> +    pub compression_name: String,
I don't think you need  to store `compression_type` and `compression_name` in the `CommonChunk` struct because it's made redundant for both AIFF and AIFC by `format_data`. Then, you would need these magic strings.

2023-06-08 17:25 UTC, dedobbin commented on symphonia-format-riff/src/riff.rs
> -        }
You are correct. I messed up merging my AIFC and AIFF branches, sloppy on my part, good catch. pushed the remaining code

2023-06-12 15:51 UTC, dedobbin commented on symphonia-format-riff/src/aiff_chunks.rs
> +}
As discussed, this is desirable, but to do this "right", it probably involves the removing of the ParseChunk trait. I think that's a good idea and want to work on this, but i think it will balloon this PR. 

I propose for now, we uses this sub-optimal solution, and i can refactor it while i work on above mentioned task.

2023-06-13 17:17 UTC, dedobbin commented on symphonia-format-riff/src/aiff_chunks.rs
> +}
Al right, as discussed we will roll with this for now but i will add TWOS support

2023-06-13 22:37 UTC, pdeljanov approved these changes

2023-06-13 22:41 UTC, merged