Add impl From<Duration> for Time and Time::into_duration
pdeljanov/Symphonia pull request #217
Opened 2023-07-10 04:48 UTC by JasonLG1979

2023-07-10 13:57 UTC, pdeljanov requested changes
Thanks for this. Can you give these suggestions a try. I believe it should improve the accuracy in extreme cases.

2023-07-10 13:57 UTC, pdeljanov commented on symphonia-core/src/units.rs
> +        StdDuration::from_secs_f64(self.seconds as f64 + self.frac)
A `f64` can only represent an unsigned integer up-to 2^52 without losing precision, so in extreme cases where seconds is very large, this conversion will be lossy.

Using `Duration::new` and passing the `u64` seconds component directly will preserve the accuracy in those extreme cases. To implement this, the fractional part must be converted to nanoseconds.

```suggestion
        StdDuration::new(self.seconds, (1_000_000_000.0 * self.frac) as u32)
```

2023-07-10 13:57 UTC, pdeljanov commented on symphonia-core/src/units.rs
> +        Time::new(seconds.trunc() as u64, seconds.fract())
Same idea about improving precision by removing the round-trip through a `f64`.

```suggestion
        Time::new(duration.as_secs(), f64::from(duration.subsec_nanos()) / 1_000_000_000.0)
```

2023-07-11 13:55 UTC, JasonLG1979 commented on symphonia-core/src/units.rs
> +use std::{fmt, time::Duration as StdDuration};
Done

2023-07-11 16:53 UTC, JasonLG1979 commented on symphonia-core/src/units.rs
> +        Time::new(seconds.trunc() as u64, seconds.fract())
Done.

2023-07-11 16:53 UTC, JasonLG1979 commented on symphonia-core/src/units.rs
> +        StdDuration::from_secs_f64(self.seconds as f64 + self.frac)
Done.

2023-07-17 03:25 UTC, pdeljanov commented
Sorry for the possible churn, I had a last second thought about this. Do you think it'd be more idiomatic if instead of `into_duration()` we add `impl From<Time> for std::time::Duration {}`? Then one would just do `some_time.into()`.

2023-07-17 03:59 UTC, JasonLG1979 commented
> Sorry for the possible churn, I had a last second thought about this. Do you think it'd be more idiomatic if instead of `into_duration()` we add `impl From<Time> for std::time::Duration {}`? Then one would just do `some_time.into()`.

It's all good. Whatever you think is best. I am by no means a judge on what is more idiomatic.

2023-07-17 04:07 UTC, JasonLG1979 commented
There is some symmetry in impl'ing From for both that I can appreciate though. But I'm not really sure if it makes it more idiomatic or not?

2023-07-17 04:16 UTC, JasonLG1979 commented
Done.

2023-07-18 02:15 UTC, pdeljanov approved these changes

2023-07-18 02:17 UTC, merged

2023-07-18 02:19 UTC, pdeljanov commented
I'm no expert either, but I do believe this very likely is the most idiomatic way. So let's go with it. Thanks for the making the changes.