Bug/aac missing timeline
pdeljanov/Symphonia pull request #222
Opened 2023-08-29 16:35 UTC by dedobbin

2023-09-06 02:52 UTC, pdeljanov commented
Could you please test this with the following command: `cat /path/to/your/aac/file.aac | symphonia-play -`.

I don't think the seek will work if the input is not a seekable file! You will need to use the seek buffer in these cases.

2023-10-10 16:50 UTC, dedobbin commented
Alright. As discussed, it now guarantees being rewindable , getting rid of the nasty panic and making it possible to set a max bytes to sample to approximate the n_frames

2024-03-05 04:42 UTC, pdeljanov commented
Getting very good results with this last set of changes!

2024-03-07 18:50 UTC, dedobbin commented
Alright, fixed all CI problems

2024-03-09 04:00 UTC, pdeljanov requested changes
This seems to cause errors when testing with `symphonia-check`. I'm assuming we're dropping a few initial packets for some reason...

2024-03-10 18:17 UTC, dedobbin commented on symphonia-codec-aac/src/adts.rs
> +            for _ in 0..=500 {
Yeah that seems on the extreme side. I was not sure what numbers to plug in, i lowered it now and it still gives acceptable output to me. Let me know if this works for you or how we should go about finding a sweet spot.

2024-03-10 23:34 UTC, pdeljanov approved these changes

2024-03-10 23:36 UTC, merged