Add initial support for Core Audio Format / CAF files
pdeljanov/Symphonia pull request #232
Opened 2023-09-19 15:38 UTC by irh

This PR introduces support for decoding `.caf` files. 

The implementation is derived from the [spec](https://developer.apple.com/library/archive/documentation/MusicAudio/Reference/CAFSpec/CAF_spec/CAF_spec.html), and tested against a local collection of audio files that use various encoding formats.

I haven't added decoding support for all chunk types, but hopefully this PR acts as a good starting point for further development?

Things seem to be working correctly, but please let me know if I've misunderstood some aspect of the format reader API, I'll be happy to make changes as needed.

2024-01-07 19:26 UTC, dedobbin commented
I tested it with files from https://filesamples.com/formats/caf and https://www.dwsamplefiles.com/download-caf-sample-files/. 
They all play correctly in symphonia-play, audio seems perfect when compared to Audacity. Track length is also correctly displayed.
Also all pass symphonia-check with default settings.

Code also looks good to me.

Good stuff.

2024-01-09 02:01 UTC, pdeljanov commented
Thanks submitting this, I can see a lot of work was put into it and we'd be happy to have it.

Generally, I think it's okay to pull in a decoder/demuxer with a minimum set of functionality. It looks like you have PCM encapsulation down, so this would be a good start.

Unfortunately, I have no knowledge or experience with CAF, so would you be willing to address any bugs that come up with it (we could assign them to you)? Also, would you like to continue extending the support to other encapsulated codecs?

2024-01-09 09:47 UTC, irh commented
Hi @dedobbin + @pdeljanov, thanks for taking a look, and I'm glad to hear that you'd be happy to accept the PR.

> Also, would you like to continue extending the support to other encapsulated codecs?

Compressed codec support is implemented (see the last commit), but maybe I misunderstood something?

What's missing from this implementation is support for metadata chunks like [markers](https://developer.apple.com/library/archive/documentation/MusicAudio/Reference/CAFSpec/CAF_spec/CAF_spec.html#//apple_ref/doc/uid/TP40001862-CH210-BCGCHAJE) or [annotations](https://developer.apple.com/library/archive/documentation/MusicAudio/Reference/CAFSpec/CAF_spec/CAF_spec.html#//apple_ref/doc/uid/TP40001862-CH210-BCGFGEAD), but I wasn't sure which features would be available through Symphonia, and I figured that support should be added with specific use cases in mind.

> Unfortunately, I have no knowledge or experience with CAF, so would you be willing to address any bugs that come up with it (we could assign them to you)?

Sure, I'd be happy to take a look if/when bugs come up, and I can review PRs with feature additions if you like.

2024-01-09 18:41 UTC, dedobbin commented on symphonia-format-caf/Cargo.toml
> +authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
I think you can add your name next to his, haha

2024-01-09 20:22 UTC, irh commented
@dedobbin I rebased the branch onto the latest master because it's been a few months (things still seem to be working correctly!), and I also fixed some clippy warnings.

2024-01-09 22:48 UTC, pdeljanov commented
Just a heads up, the format check is failing because our config requires the nightly toolchain to adjust the bracket style. If you install the nightly toolchain you can use it by adding `+nightly` after `cargo`, e.g., `cargo +nightly fmt`.

2024-01-10 11:05 UTC, irh commented
@pdeljanov I've run `cargo +nightly fmt` and pushed.

2024-01-11 04:09 UTC, pdeljanov requested changes
I've completed a more thorough review of this PR. While going over this I used [Apple's specification](https://developer.apple.com/library/archive/documentation/MusicAudio/Reference/CAFSpec/CAF_intro/CAF_intro.html#//apple_ref/doc/uid/TP40001862-CH203-TPXREF101) as a reference.

Overall, I think this is very nicely done! Hopefully we can get this in very soon. :smile: 

Most of my concerns are related to data validation. The media stream should be considered untrustworthy and even malicious. Therefore, it's important we don't blindly trust what is being read. Less sinister scenarios could include damaged files. Ultimately, we don't ever want to panic or get thrown into an infinite loop due to bad input. Consider checking out the fuzzing setup used for MP3 if you really want to stress your code. That being said, I'm not going to gate this review on fuzz tests.

2024-01-11 04:09 UTC, pdeljanov commented on symphonia-format-caf/src/demuxer.rs
> +            error!("unsupported file version ({file_version})");
Named parameters in format strings are introduced in Rust 1.58, but the MSRV for Symphonia v0.5.x is Rust 1.53. Since you are a new and optional feature we could let this slide, but it messy things a bit.

2024-01-12 20:52 UTC, irh commented on symphonia-format-caf/src/chunks.rs
> +            b"kuki" => Chunk::MagicCookie(reader.read_boxed_slice_exact(chunk_size as usize)?),
Yes good point, I've added additional size checks.

2024-01-12 20:52 UTC, irh commented on symphonia-format-caf/src/chunks.rs
> +            channels_per_frame: reader.read_be_u32()?,
There's a check for the channel count being zero in `CafReader::read_audio_description_chunk()`, but I think it makes sense to report an error as soon as possible. Does it make sense to leave the extra check in place (I guess the alternative is replacing it with `unreachable!()`)?

2024-01-12 20:52 UTC, irh commented on symphonia-format-caf/src/chunks.rs
> +        self.bytes_per_packet == 0 || self.frames_per_packet == 0
This is an `or` check which I thought would cover all compressed cases, but actually in the spec it says ["... for compressed formats the mBitsPerChannel field is always 0"](https://developer.apple.com/library/archive/documentation/MusicAudio/Reference/CAFSpec/CAF_spec/CAF_spec.html#//apple_ref/doc/uid/TP40001862-CH210-BCGFDIGI), so I think that should be a sufficient check?

2024-01-12 20:52 UTC, irh commented on symphonia-format-caf/src/chunks.rs
> +        if chunk_size < edit_count_offset {
Good catch 👍

2024-01-12 20:52 UTC, irh commented on symphonia-format-caf/src/chunks.rs
> +            1 => return Channels::from_bits(self.channel_bitmap),
Good catch 👍

2024-01-12 20:52 UTC, irh commented on symphonia-format-caf/src/chunks.rs
> +    loop {
Good idea 👍

2024-01-12 20:52 UTC, irh commented on symphonia-format-caf/src/demuxer.rs
> +                    return decode_error("Invalid packet index");
Done, although I couldn't build with 1.53 to check that I haven't used any other post-1.53 features (there's a problem with finding a supported version of `regex`).

2024-01-12 21:01 UTC, irh commented
Thanks for the review @pdeljanov, I've followed up on your feedback and pushed the changes, although I haven't double checked against my test files yet. I should have time to check them out over the weekend, I'll follow up when I'm done.

2024-01-13 01:50 UTC, pdeljanov approved these changes

2024-01-13 01:50 UTC, pdeljanov commented on symphonia-format-caf/src/chunks.rs
> +        if chunk_size != -1 && chunk_size_u64 < edit_count_offset {
Suggestion: I feel this check is a bit too clever and harms readability a bit. Atleast until one recalls signed two's complement. Consider doing it the more "naive" way.

2024-01-13 01:50 UTC, pdeljanov commented on symphonia-format-caf/src/chunks.rs
> +            channels_per_frame: reader.read_be_u32()?,
Either way works for me.

In such cases, I think I'd only strongly prefer the latter over the former if the additional check was in a hot code path. Mainly because we already setup the precondition that the field will never be `0` so why waste the cycles? However, I don't think `FormatReaders` are ever really "hot" so you can choose whatever you think is best for maintainability.

2024-01-13 01:50 UTC, pdeljanov commented on symphonia-format-caf/src/chunks.rs
> +        self.bytes_per_packet == 0 || self.frames_per_packet == 0
Yeah, that seems like a stronger guarantee. Let's see how it works out!

2024-01-13 01:59 UTC, pdeljanov commented on symphonia-format-caf/src/demuxer.rs
> +                    return decode_error("Invalid packet index");
Ah, I see. The `regex` crate is being pulled in by `env_logger` which is used by `symphonia-play` and `symphonia-check`, but not the main libraries. I tried building with 1.53.0 though, and it seems the `log` crate now requires 1.60.0, so this is unfortunate. We can ignore this then.

2024-01-13 02:04 UTC, pdeljanov commented
Hey @irh,

Thanks, looks good to me! We can merge this when you're ready.

Before then, you should also add yourself to the `CONTRIBUTORS` file. Also, if you can, please update the feature tables in `/README.md`, `/symphonia/README.md`, and `/symphonia/src/lib.rs`. Since this is the initial release, `symphonai-format-caf` should have a `Good` rating.

2024-01-15 08:06 UTC, irh commented on symphonia-format-caf/src/chunks.rs
> +            channels_per_frame: reader.read_be_u32()?,
I think for maintainability replacing the error with an assertion makes sense, otherwise the maintainer is left wondering if there's ever a case where the first check could pass and then the second check could fail. There's no such case, so an assertion communicates that more clearly.

2024-01-15 08:15 UTC, irh commented on symphonia-format-caf/src/chunks.rs
> +        if chunk_size != -1 && chunk_size_u64 < edit_count_offset {
You're right, I've tried to simplify this a bit.

2024-01-15 08:16 UTC, irh commented
OK thanks for taking the time to review this and for the great feedback, I think we're good to go 👍

2024-01-15 23:35 UTC, pdeljanov commented
Sounds good @irh! Do you mind re-basing this to resolve the conflicts?

2024-01-16 13:43 UTC, merged

2024-01-16 13:44 UTC, pdeljanov commented
Merged! Thank you for the work you put into this!