isomp4: set mdhd.duration with adjusted timescale, reverts PR #317
pdeljanov/Symphonia pull request #332
Opened 2024-12-27 21:42 UTC by sscobici

the approach taken in PR #317 doesn't allow to adjust duration to mdhd timescale, so I reverted the changes and modified only moov atom

Please advise what code I can reuse to avoid/reduce the risk of multiplication overflow during the timescale conversion.
I found some logic in core\units.rs but didn't find it easy to reuse.

2025-01-15 19:22 UTC, sscobici commented
will mark this as draft, waiting for mp4 refactoring

2026-03-25 06:12 UTC, valarauca commented
This doesn't appear to handle edits?

2026-03-25 20:25 UTC, sscobici commented
Hi,

Symphonia doesn't currently account for edit lists during MP4 playback. With these edits, a file's duration might be reported as 10s even if it only contains 1s of actual audio/video frames.

I’ve reviewed your proposed changes and noticed there is also a fix in version 0.5. I’ll try adjust this PR to fix MP4 duration in 0.6, though it won't include support for edits or streaming yet. Unless you already have a PR opened.

2026-03-28 17:20 UTC, sscobici commented
This PR corrects errors introduced in my previous PR #317.

**Future Work (outside of this PR)**
1. For fragmented file when segment index is not present duration needs to be calculated from Movie Fragments or Track Fragments. This is currently not implemented as it would increase initial parsing time.
2. Currently ignores edits (edts). Demuxer should also be adjusted
3. Does not populate track duration directly; only `num_frames` is populated, maintaining consistency with other demuxers.

**Related Issues**
- Partially fixes #475.

**Credits**
- Applies the fix from 0.5 #440, but implemented at a different level
- Applies the fix from #459 but inside the moov atom

2026-04-24 03:29 UTC, pdeljanov reviewed
Thanks for attempting these fixes.

I left some comments for things I'd like to see changed, but also looking for some clarifications to help my understanding.

On an aside, you have 4 PRs open right now, but this is the only non-draft one. Is this the only one you'd like to land in 0.6?

2026-04-24 03:29 UTC, pdeljanov commented on symphonia-core/src/units.rs
> +
Let's not add this too core, it's not integrated with anything else in `units`. If there is a need for it to be in core in the future, it can moved later.

2026-04-24 03:29 UTC, pdeljanov commented on symphonia-format-isomp4/src/atoms/moov.rs
> +                trak.mdia.mdhd.duration = trak.mdia.minf.stbl.stts.total_duration;
This is for consistency since we don't support edits? If there aren't any edits, then these values should be roughly equal as far as I understand.

2026-04-24 03:29 UTC, pdeljanov commented on symphonia-format-isomp4/src/atoms/trak.rs
> -            if mdia_atom.mdhd.duration != 0 { mdia_atom.mdhd.duration } else { tkhd_atom.duration };
Ah. This would've been wrong. The TKHD duration is in the movie timescale rather than the track's timescale.

2026-04-24 03:29 UTC, pdeljanov commented on symphonia-format-isomp4/src/demuxer.rs
> +                        // select the index with the earliest presentation timestamp to be the first.
Do we even need to hold onto `sidx` anymore? It's only used to print an information message if it's `Some`. Instead, you can just see if the hashmap contains atleast 1 entry.

2026-04-24 03:29 UTC, pdeljanov commented on symphonia-format-isomp4/src/demuxer.rs
> +            };
Can we not do a crazy match for this? ;)

How about this:

```rust
let timespan = sidx_timespans
    .get(&trak.tkhd.id)
    .filter(|_| moov.is_fragmented())
    .map(|sidx_ts| TimeSpan::new(sidx_ts.timescale, sidx_ts.duration))
    .unwrap_or_else(|| {
        TimeSpan::new(trak.mdia.mdhd.timescale, trak.mdia.mdhd.duration)
    });
```

2026-04-24 03:29 UTC, pdeljanov commented on symphonia-format-isomp4/src/stream.rs
> +        false
Are we sure about that? Isn't that why we are summing the duration in the segment index?

2026-04-24 10:51 UTC, sscobici commented on symphonia-core/src/units.rs
> +
ok, moved to demuxer

2026-04-24 12:24 UTC, sscobici commented on symphonia-format-isomp4/src/atoms/moov.rs
> +                trak.mdia.mdhd.duration = trak.mdia.minf.stbl.stts.total_duration;
Thanks for challenging this. I removed this change. In #440 the code tries to fill duration from stts.total_duration when mdhd.duration is 0, but I'm not sure this is a good idea. We should keep mdhd.duration as it is and just not use during seeking / parsing as it is often different from stts.total_duration (don't know the real reason for this, maybe edits).

mdhd.duration 0 is a valid case for fragmented mp4, because stts.total_duration is also zero in that case.

2026-04-24 12:26 UTC, sscobici commented on symphonia-format-isomp4/src/demuxer.rs
> +                        // select the index with the earliest presentation timestamp to be the first.
removed sidx variable, but this PR doesn't store the sidx atoms for further reuse - just calculates the total duration

2026-04-24 12:42 UTC, sscobici commented on symphonia-format-isomp4/src/demuxer.rs
> +            };
yes, adjusted.

Seems that format::Track object needs an enhancement.
If we want it to have both num_frames (expressed in media timebase) and duration (expressed in movie timebase), then we need two timebases or use two TimeSpan objects.
MediaTimeSpan can be 2 seconds expressed in media timescale
TrackTimeSpan can be 10 seconds expressed in movie timescale due to edits which can repeat media 5 times.

If we have single timescale we need to transform trak.tkhd.duration into media timescale.

2026-04-24 16:38 UTC, sscobici commented on symphonia-format-isomp4/src/stream.rs
> +        false
Some fragmented MP4 files lack a segment index (sidx). In such cases, if the file is seekable, it is possible to parse all movie fragments (moof) to calculate the total track duration (not sure we need this). However, if a fragmented file is non-seekable and lacks a segment index, the duration must be treated as infinite.

        // If all tracks ended in the last segment, then do not try to read anymore segments.
        // Note, there will always be one segment because the moov atom was converted into a segment
        // when the reader was instantiated.
        if self.segs.last().unwrap().all_tracks_ended() {
            return Ok(false);
        }

This check is unreliable for fragmented files. Even after reaching the end of a movie segment, the demuxer must attempt to read the next one—particularly when the total stream duration is unknown

2026-04-24 16:48 UTC, sscobici commented
> On an aside, you have 4 PRs open right now, but this is the only non-draft one. Is this the only one you'd like to land in 0.6?

#493 has some minor changes, it will be good if it is merged.
#301 I need to review it, it has some memory and panics fixes, but I need to understand the approach to memory limits in demuxers.
#333 doesn't contain all my local changes but it is very useful for me to test Info against mediainfo and video pts / dts against ffmpeg.

I have some local draft for video PTS calculations but I need more time to get is equivalent to ffmpeg (seems I forgot edits).

----------------
I added setting duration for format::Track in the media timescale. Many files have it populated considering edits.
Seems like symphonia is not good at playing back the files with edits right now and for video files it is often used to sync up audio and video at the start.

2026-04-24 16:50 UTC, sscobici commented on symphonia-format-isomp4/src/atoms/trak.rs
> -            if mdia_atom.mdhd.duration != 0 { mdia_atom.mdhd.duration } else { tkhd_atom.duration };
will try to run some local tests to catch these kind of regressions in future

2026-04-27 04:30 UTC, pdeljanov commented
> #493 has some minor changes, it will be good if it is merged.

I'll take a look. Seems pretty minimal and straightforward, so let's see if we can get that one for 0.6.

> #301 I need to review it, it has some memory and panics fixes, but I need to understand the approach to memory limits in demuxers.

This one is based off of the old `dev-0.6` so it's missing the `AtomIterator` rewrite that ended up in `main`. I think a lot of the improvements will have been incorporated in the rewrite. Notably, the `AtomIterator` now acts as a scoped reader, so it's no longer possible to read past the end of an atom. However, there may be so smaller things I missed.

---

I'd like to align on some things regarding timing. In 0.6, we now make a distinction between number of frames and the duration.

The number of frames is the number of decoded audio or video frames, excluding any delay or padding frames (audio only). It is a count, and there is no timebase for it. For users who want to know the total number of decoded frames including discarded, they can add in the delay and padding fields of `CodecParameters`.

The duration is the running time of the track, as stated by the container, in timebase units, excluding any delay or padding frames. Likewise, DTS and PTS are also in timebase units and represent instants along the duration of the track.

Since Symphonia was historically audio-focused, duration and number of frames were often used interchangeably. 
This is because most of the containers did not explicitly state a timebase. So, I chose to use `1 / sample_rate` as the timebase which in turn makes duration and number of frames equal. However, MP4 specifies a timescale, and MKV states durations in nanoseconds. So we can't do this for them.

So, all this to say, for containers that don't specify a timebase, populating the duration of the track with number of frames is completely valid wherever we set the timebase to be `1 / sample_rate`, which is all containers except MKV and MP4.

What may be missing is the concept of an overall media (all track) duration, timebase, etc. I'm not sure how to fit this in with the per-track duration, timebase, etc.

Does this track with your understanding?

2026-05-01 07:09 UTC, sscobici commented
> So, all this to say, for containers that don't specify a timebase, populating the duration of the track with number of frames is completely valid wherever we set the timebase to be 1 / sample_rate, which is all containers except MKV and MP4.

I agree. I've added a commit to set the duration as num_frames for other containers; for MKV, there is a better implementation in #494.

> What may be missing is the concept of an overall media (all track) duration, timebase, etc. I'm not sure how to fit this in with the per-track duration, timebase, etc.

I believe general file/stream information should live at the Format level (Readers). We need to define a struct and specify which fields are relevant, and each demuxer will populate them. For now, this PR assumes the track timebase is the media timebase (non general) and handles the conversion for MP4 track durations, which are expressed in the container's general timebase.

2026-05-08 17:41 UTC, sscobici commented
Added setting of media_info.

2026-05-11 04:38 UTC, pdeljanov requested changes
I think I'd like for this to be the last PR that goes in for 0.6, however, there is a blocking and correctness issue.

I do want to push 0.6 out in a day or two, so let me know if you want me to handle the corrections.

2026-05-11 04:38 UTC, pdeljanov commented on symphonia-format-isomp4/src/demuxer.rs
> +            let mvhd_timespan = TimeSpan::new(trak.mdia.mdhd.timescale, trak.mdia.mdhd.duration);
This confused me for a bit because `mvhd_timespan` should be called `mdhd_timespan` or `mdia_timespan` since `mvhd` implies a different timescale all together.

2026-05-11 04:38 UTC, pdeljanov commented on symphonia-format-isomp4/src/stream.rs
> +        false
The blocking issue is that I have fragmented files (downloaded from YT) with a segment index, however, with this PR they now return an `Err(EOF)` rather than `Ok(None)` when being piped in via. stdin. Since this is a case with a segment index, it should return `Ok(None)` which means this shouldn't just return `false` in all cases.

What are the cases the existing code became unreliable? Was it the assumption that if a track is not present in the fragment then it must have ended? Are you able to share some samples?

2026-05-11 04:38 UTC, pdeljanov commented on symphonia-format-isomp4/src/demuxer.rs
> +                    )
FYI, this is going to be wrong if there are edits as the `trak.tkhd.duration` field is going to the be duration of all the edits. Otherwise, it should be equal the total duration of all samples. Since we don't support edits, then it would make the most sense to just use the total duration of all samples as that also handles the `trak.tkhd.duration == 0` case. However, you should leave a TODO indicating that here and maybe even the commented out code.

2026-05-14 04:04 UTC, pdeljanov commented
Update: I'm quite eager to release 0.6, but without some of the modifications made in this PR MP4 wouldn't be in good shape. So I've been working on a commit based on the changes in this PR (with some modifications based on my comments above) and will likely commit those. I'll make us co-authors on that commit so you will get appropriate attribution.

2026-05-15 03:49 UTC, pdeljanov commented
Closing this now since ad5f2d7f117523bdb8e18c3bf7e23fc933afa946 builds upon this PR and with a few adjustments.

2026-05-15 03:49 UTC, closed without merging

2026-05-15 07:00 UTC, sscobici commented
thanks for merging.