opus: handle identification header.
pdeljanov/Symphonia pull request #59
Opened 2021-09-30 08:31 UTC by thinking-tower

@pdeljanov, could you create another branch for Opus? The `opus` should be kept for reference for now. 

# Description
Part of the work for #8.

Porting over code from `opus` branch and verifying that it matches [RFC 7845](https://tools.ietf.org/pdf/rfc7845.pdf).

2021-10-02 02:04 UTC, pdeljanov commented
Hey @thinking-tower, I made a new `opus-dev` branch for this work. I can delete the old `opus` branch once all the existing code is ported over to prevent any confusion.

2021-10-03 04:04 UTC, thinking-tower commented
@pdeljanov Awesome, could you review this PR?

2021-10-03 16:35 UTC, pdeljanov requested changes

2021-10-04 03:31 UTC, pdeljanov commented
Hi @thinking-tower, please see the review comment. Everything else looks okay to me.

2021-10-05 06:12 UTC, thinking-tower commented
@pdeljanov I've changed the names of the test to be shorter than `100` characters, with longest being `62` characters long.

2021-10-05 13:45 UTC, pdeljanov approved these changes

2021-10-05 13:45 UTC, merged

2021-10-05 13:49 UTC, pdeljanov commented
Thanks, I've merged this now!

A suggestion for next time though: try not to rebase your PR branch and force push since it makes viewing changes impossible and removes the approval to run the CI automatically. I generally always squash PR branches into a single commit before merging so there's no need to worry about a messy history.

Cheers!